---
title: "Homework 1"
author: Liz Park
output: github_document
---

This is my solution to HW1.

```{r}
library(tidyverse)
```


## Problem 1

Create a data frame with the specified elements.

```{r}
prob1_df =
    tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b" , "c" , "d" , "e" , "f" , "g" , "h" , "i" , "j"),
    factor_vec= factor(c("low" , "low" , "low" , "mod" , "mod" , "mod" , "mod" , "high" , "high" , "high"))
)
```

Take the mean of each variable in my data frame.

```{r mean_pull_var}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```
I can take the mean of numbers and logical but not character or factor.


```{r try_numeric}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

```{r, try_multiply}
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```
```{r, eval=F, echo=T}
as.character(pull(prob1_df, samp_gt_0),factor)* pull(prob1_df, samp)
as.numeric(as.character(pull(prob1_df, samp_gt_0),factor))* pull(prob1_df, samp)
```

```


## Problem 2
install.packages("palmerpenguins")
data("penguins", package = "palmerpenguins")

```{r}
library(tidyverse)
```

##In this penguins dataset:

* Species, island, bill length mm, bill depth mm, flipper length mm, body mass g, sex, and year are reported
* There are 344 rows and 8 columns
* Mean penguin flipper length is 200.9152 mm


nrow(penguins)
ncol(penguins)

mean(penguins$flipper_length_mm,na.rm=TRUE)
```


ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color=species)) + geom_point()
ggsave("scatterpenguin_plot.pdf", height = 4, width = 6)

